server:
    port: 8080
    contextPath: /riscozero/

security.basic.enable: false
management.security.enabled: false

---
spring:
    profiles: local,default
    mvc:
        throw-exception-if-no-handler-found: true

datasource:
    riscozero:
        url: jdbc:mysql://localhost:3306/riscozero
        username: root
        password: rabbit
        driverClassName: com.mysql.jdbc.Driver
        defaultSchema:
        hibernate:
            hbm2ddl.method: update
            show_sql: true
            format_sql: true
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
